config/routes.rb
Gdsit::Application.routes.draw do
  get 'admin' => 'computers#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  get "home/index"

  resources :computers

  post "computers/select_db"

  get "computers/select_show"

  root :to => 'sessions#new'

end

app/models/computer.rb
class Computer < ActiveRecord::Base
  validates :leixing, :pc, :name, :number, :department, :user, :city, :date, :product,
            :cpu, :memory, :disk, :mouse, :wired, :sn, :os, :token, :other, :presence => true
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present

  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end


  def password=(password)
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private
  def password_must_be_present
    errors.add(:password, "Missing password") unless hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
   # @total_orders = Order.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_filter :authorize
  protect_from_forgery

  protected
  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to login_url, :notice => "Please log in"
    end
  end
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :update, :destroy]
  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @computers }
    end
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
    @computer = Computer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @computer }
    end
  end

  # GET /computers/new
  # GET /computers/new.json
  def new
    @computer = Computer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @computer }
    end
  end

  # GET /computers/1/edit
  def edit
    @computer = Computer.find(params[:id])
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(params[:computer])

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render json: @computer, status: :created, location: @computer }
      else
        format.html { render action: "new" }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /computers/1
  # PUT /computers/1.json
  def update
    @computer = Computer.find(params[:id])

    respond_to do |format|
      if @computer.update_attributes(params[:computer])
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer = Computer.find(params[:id])
    @computer.destroy

    respond_to do |format|
      format.html { redirect_to computers_url }
      format.json { head :no_content }
    end
  end

  def select_db
    if
      @computer = Computer.where(params[:select_a] => params[:select_c])
      render :action => "select_show"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new
  end

  def create
    if user = User.authenticate(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, :alert => "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_url,
                                  :notice => "User #{@user.name} was successfully created.") }
        format.xml { render :xml => @user,
                            :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user.errors,
                            :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url,
                                  :notice => "User #{@user.name} was successfully updated.") }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors,
                            :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/computers/_form.html.erb
<%= form_for(@computer) do |f| %>
  <% if @computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% @computer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :leixing, '类别' %><br />
    <%= f.text_field :leixing %>
  </div>
  <div class="field">
    <%= f.label :pc, '计算机名' %><br />
    <%= f.text_field :pc %>
  </div>
  <div class="field">
    <%= f.label :name, '名称' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number, '资产编号' %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :department, '使用部门' %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :user, '使用人' %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :city, '城市' %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :date, '生产日期' %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :product, '品牌型号规格' %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :cpu %><br />
    <%= f.text_field :cpu %>
  </div>
  <div class="field">
    <%= f.label :memory, '内存' %><br />
    <%= f.text_field :memory %>
  </div>
  <div class="field">
    <%= f.label :disk , '硬盘' %><br />
    <%= f.text_field :disk %>
  </div>
  <div class="field">
    <%= f.label :mouse, '鼠标' %><br />
    <%= f.select :mouse, [['有',1],['无',0]], {:include_blank=>true,:selected=>0} %>
  </div>
  <div class="field">
    <%= f.label :wired, '有线网卡Mac地址' %><br />
    <%= f.text_field :wired %>
  </div>
  <div class="field">
    <%= f.label :wife, '无线网卡Mac地址' %><br />
    <%= f.text_field :wife %>
  </div>
  <div class="field">
    <%= f.label :sn, 'S/N' %><br />
    <%= f.text_field :sn %>
  </div>
  <div class="field">
    <%= f.label :os, '预装操作系统' %><br />
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :token, '令牌' %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :other, '备注' %><br />
    <%= f.text_field :other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<h1>修改资产</h1>

<%= render 'form' %>

<%= link_to '显示', @computer %> |
<%= link_to '返回', computers_path %>

app/views/computers/index.html.erb
<h4>GDS计算机资产统计</h4>
<br>

<p>
<%= form_tag "computers/select_db" do %>
    <%= select_tag :select_a, "<option value='pc'>计算机名</option><option value='user'>使用人</option><option value='department'>部门</option><option value='sn'>S/N</option>".html_safe %>
    <%= text_field_tag [:select_c] %>
    <%= submit_tag (value = "查询") %>
<% end %>
</p>

<table class="table table-striped">
  <tr>
    <th>类别</th>
    <th>计算机名</th>
    <th>名称</th>
    <th>资产编号</th>
    <th>使用部门</th>
    <th>使用人</th>
    <th>城市</th>
    <th>生产日期</th>
    <th>品牌型号规格</th>
    <th>Cpu</th>
    <th>内存</th>
    <th>硬盘</th>
    <th>鼠标</th>
    <th>有线网卡Mac地址</th>
    <th>无线网卡Mac地址</th>
    <th>S/N</th>
    <th>预装操作系统</th>
    <th>令牌</th>
    <th>备注</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @computers.each do |computer| %>
  <tr>
    <td><%= computer.leixing %></td>
    <td><%= computer.pc %></td>
    <td><%= computer.name %></td>
    <td><%= computer.number %></td>
    <td><%= computer.department %></td>
    <td><%= computer.user %></td>
    <td><%= computer.city %></td>
    <td><%= computer.date %></td>
    <td><%= computer.product %></td>
    <td><%= computer.cpu %></td>
    <td><%= computer.memory %></td>
    <td><%= computer.disk %></td>
    <td><%= computer.mouse %></td>
    <td><%= computer.wired %></td>
    <td><%= computer.wife %></td>
    <td><%= computer.sn %></td>
    <td><%= computer.os %></td>
    <td><%= computer.token %></td>
    <td><%= computer.other %></td>
    <td><%= link_to 'Show', computer %></td>
    <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
    <td><%= link_to 'Destroy', computer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<div class="btn">
<%= link_to '新增', new_computer_path %>
</div>

app/views/computers/new.html.erb
<h4>新增一笔资产</h4>
<br>

<%= render 'form' %>

<%= link_to '返回', computers_path %>

app/views/computers/select_show.html.erb
<table class="table table-striped">
  <tr>
    <th>类别</th>
    <th>计算机名</th>
    <th>名称</th>
    <th>资产编号</th>
    <th>使用部门</th>
    <th>使用人</th>
    <th>城市</th>
    <th>生产日期</th>
    <th>品牌型号规格</th>
    <th>Cpu</th>
    <th>内存</th>
    <th>硬盘</th>
    <th>鼠标</th>
    <th>有线网卡Mac地址</th>
    <th>无线网卡Mac地址</th>
    <th>S/N</th>
    <th>预装操作系统</th>
    <th>令牌</th>
    <th>备注</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @computer.each do |computer| %>
  <tr>
    <td><%= computer.leixing %></td>
    <td><%= computer.pc %></td>
    <td><%= computer.name %></td>
    <td><%= computer.number %></td>
    <td><%= computer.department %></td>
    <td><%= computer.user %></td>
    <td><%= computer.city %></td>
    <td><%= computer.date %></td>
    <td><%= computer.product %></td>
    <td><%= computer.cpu %></td>
    <td><%= computer.memory %></td>
    <td><%= computer.disk %></td>
    <td><%= computer.mouse %></td>
    <td><%= computer.wired %></td>
    <td><%= computer.wife %></td>
    <td><%= computer.sn %></td>
    <td><%= computer.os %></td>
    <td><%= computer.token %></td>
    <td><%= computer.other %></td>
    <td><%= link_to 'Show', computer %></td>
    <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
    <td><%= link_to 'Destroy', computer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>类别:</b>
  <%= @computer.leixing %>
</p>

<p>
  <b>计算机名:</b>
  <%= @computer.pc %>
</p>

<p>
  <b>名称:</b>
  <%= @computer.name %>
</p>

<p>
  <b>资产编号:</b>
  <%= @computer.number %>
</p>

<p>
  <b>使用部门:</b>
  <%= @computer.department %>
</p>

<p>
  <b>使用人:</b>
  <%= @computer.user %>
</p>

<p>
  <b>城市:</b>
  <%= @computer.city %>
</p>

<p>
  <b>生产日期:</b>
  <%= @computer.date %>
</p>

<p>
  <b>品牌型号规格:</b>
  <%= @computer.product %>
</p>

<p>
  <b>Cpu:</b>
  <%= @computer.cpu %>
</p>

<p>
  <b>内存:</b>
  <%= @computer.memory %>
</p>

<p>
  <b>硬盘:</b>
  <%= @computer.disk %>
</p>

<p>
  <b>鼠标:</b>
  <%= @computer.mouse %>
</p>

<p>
  <b>有线网卡Mac地址:</b>
  <%= @computer.wired %>
</p>

<p>
  <b>无线网卡Mac地址:</b>
  <%= @computer.wife %>
</p>

<p>
  <b>S/N:</b>
  <%= @computer.sn %>
</p>

<p>
  <b>预装操作系统:</b>
  <%= @computer.os %>
</p>

<p>
  <b>令牌:</b>
  <%= @computer.token %>
</p>

<p>
  <b>备注:</b>
  <%= @computer.other %>
</p>


<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>

app/views/home/index.html.erb
<h1>GDS计算机资产统计系统</h1>
<p><%= link_to '点击进入', computers_path() %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Gdsit</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>

    <!-- Le styles -->
    <link href="./css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="./css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><%= image_tag('gdsit.png', :class => 'list_image') %></a>
        </div>
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="./bootstrap/js/jquery.js"></script>
    <script src="./bootstrap/js/bootstrap-transition.js"></script>
    <script src="./bootstrap/js/bootstrap-alert.js"></script>
    <script src="./bootstrap/js/bootstrap-modal.js"></script>
    <script src="./bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="./bootstrap/js/bootstrap-scrollspy.js"></script>
    <script src="./bootstrap/js/bootstrap-tab.js"></script>
    <script src="./bootstrap/js/bootstrap-tooltip.js"></script>
    <script src="./bootstrap/js/bootstrap-popover.js"></script>
    <script src="./bootstrap/js/bootstrap-button.js"></script>
    <script src="./bootstrap/js/bootstrap-collapse.js"></script>
    <script src="./bootstrap/js/bootstrap-carousel.js"></script>
    <script src="./bootstrap/js/bootstrap-typeahead.js"></script>

  </body>
</html>

app/views/users/_form.html.erb
<div class="depot_form">
  <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %>
              prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <fieldset>
        <legend>管理员注册</legend>
        <div>
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, :size => 40 %>
        </div>
        <div>
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, :size => 40 %>
        </div>
        <div>
          <%= f.label :password_confirmation, 'Confirm'%>
          <%= f.password_field :password_confirmation, :size => 40 %>
        </div>
        <div>
          <%= f.submit %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h4>管理员列表</h4>
<br>

<% if notice %>
<p id="notice" ><%= notice %></p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>管理员名</th>
    <th>Hashed password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.hashed_password %></td>
    <td><%= user.salt %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h4>新增管理员</h4>

<br>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>